version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=reporter
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata-reporter:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./client:/app
volumes:
  pgdata-reporter:
